version: "3.9"

name: visual-agent-rag

services:
  weaviate:
    image: semitechnologies/weaviate:1.25.8
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      AUTHORIZATION_ADMINLIST_ENABLED: "false"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: ""
      QUERY_DEFAULTS_LIMIT: 25
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - weaviate_data:/var/lib/weaviate
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/v1/.well-known/ready >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - ragnet

  app:
    # API ligera
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      weaviate:
        condition: service_healthy
    environment:
      WEAVIATE_URL: http://weaviate:8080
      WEAVIATE_API_KEY: ""
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      DEFAULT_QUERY_IMAGE: SYNTH/img_0001.jpg
      PORT: "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./app/static:/app/app/static
    networks:
      - ragnet
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/health >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    ports:
      - "27017:27017"        # opcional exponerlo al host
    volumes:
      - mongo_data:/data/db
    networks:
      - ragnet

  indexer:
    command: bash -lc "python -m app.indexer"

    build:
      context: .
      dockerfile: Dockerfile.indexer
    restart: "no"
    depends_on:
      weaviate:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      # FiftyOne -> usa el mongo del compose
      FIFTYONE_DATABASE_URI: mongodb://mongo:27017

      FO_DATASET_NAME: fashion_demo
      FO_USE_EXISTING: "false"
      FO_ZOO_DATASET: fashion-mnist
      FO_ZOO_SPLIT: test
      FO_MAX_SAMPLES: "1000"

      FO_EMB_FIELD: clip_embedding
      FO_CLIP_MODEL: clip-vit-base32-torch

      WEAVIATE_URL: http://weaviate:8080
      WEAVIATE_API_KEY: ""
      WVT_CLASS: FashionItem
      BATCH_SIZE: "128"
      INDEX_LIMIT: "1000"
    volumes:
      - ./data:/app/data
      - fiftyone_data:/root/fiftyone   
      - ./fiftyone_config.json:/root/.fiftyone/config.json:ro   
    networks:
      - ragnet


volumes:
  weaviate_data:
  mongo_data:
  fiftyone_data:

networks:
  ragnet:
    driver: bridge
