version: "3.9"

name: visual-agent-rag

services:
  weaviate:
    image: semitechnologies/weaviate:1.25.8
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      AUTHORIZATION_ADMINLIST_ENABLED: "false"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: ""
      QUERY_DEFAULTS_LIMIT: 25
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - weaviate_data:/var/lib/weaviate
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/v1/.well-known/ready >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - ragnet

  app:
    # API ligera
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      weaviate:
        condition: service_healthy
    environment:
      WEAVIATE_URL: http://weaviate:8080
      WEAVIATE_API_KEY: ""
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      DEFAULT_QUERY_IMAGE: SYNTH/img_0001.jpg
      PORT: "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./app/static:/app/app/static
    networks:
      - ragnet
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/health >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  indexer:
    # Imagen separada para FiftyOne/Torch
    build:
      context: .
      dockerfile: Dockerfile.indexer
    restart: "no"  # No reiniciar automáticamente
    depends_on:
      weaviate:
        condition: service_healthy
    environment:
      # FiftyOne
      FO_DATASET_NAME: fashion_demo
      FO_USE_EXISTING: "false"          # true si ya existe el dataset
      FO_ZOO_DATASET: deepfashion      
      FO_ZOO_SPLIT: validation
      FO_MAX_SAMPLES: "1000"

      # Embeddings (si usas indexer con FO Brain; si usas CLIP propio, ignora)
      FO_EMB_FIELD: clip_embedding
      FO_CLIP_MODEL: clip-vit-base32-torch

      # Weaviate
      WEAVIATE_URL: http://weaviate:8080
      WEAVIATE_API_KEY: ""
      WVT_CLASS: FashionItem
      BATCH_SIZE: "128"

      # Límite de indexado al usar indexer CLIP propio
      INDEX_LIMIT: "1000"
    command: >
      bash -lc "python -m app.indexer"
    volumes:
      - ./data:/app/data
    networks:
      - ragnet
    # Para GPU (si tu imagen base soporta CUDA):
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]

volumes:
  weaviate_data:

networks:
  ragnet:
    driver: bridge
