version: "3.9"
services:
  visual-agents-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
    command: uvicorn app.main:app --host  