from typing import Protocol, List, Dict, Any

class EmbedderTool(Protocol):
    def embed_image(self, image_path: str) -> List[float]: ...

class DatasetTool(Protocol):
    def sample_paths(self, limit: int = 200) -> List[str]: ...
    def get_metadata(self, filepath: str) -> Dict[str, Any]: ...

class VectorStoreTool(Protocol):
    def index(self, vectors: List[List[float]], payloads: List[Dict[str, Any]]) -> None: ...
    def query(self, vector: List[float], k: int = 10) -> List[Dict[str, Any]]: ...

class EnricherTool(Protocol):
    def enrich(self, items: List[Dict[str, Any]]) -> List[Dict[str, Any]]: ...
